apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus
  namespace: default
spec:
  project: default
  sources:
  - repoURL: https://redhat-developer.github.io/redhat-helm-charts
    chart: quarkus
    targetRevision: "0.0.3"
    helm:
      valueFiles:
      - $values/multi-source-argocd/quarkus-values.yaml
  - repoURL: https://github.com/luismiguelzapata/gitops-examples
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: javademo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
