apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary
  namespace: default
spec:
  project: default
  source:
    path: argo-rollouts/canary/overlays/localhost
    repoURL: 'https://github.com/luismiguelzapata/gitops-examples'
    targetRevision: main
  destination:
    namespace: canary
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
